servers localhost:11221,localhost:11222,localhost:11223,localhost:11224,localhost:11225,
	localhost : 11221
	localhost : 11222
	localhost : 11223
	localhost : 11224
	localhost : 11225

Error 0 -> SUCCESS
Error 1 -> FAILURE
Error 2 -> HOSTNAME LOOKUP FAILURE
Error 3 -> CONNECTION FAILURE
Error 4 -> CONNECTION BIND FAILURE
Error 5 -> WRITE FAILURE
Error 6 -> READ FAILURE
Error 7 -> UNKNOWN READ FAILURE
Error 8 -> PROTOCOL ERROR
Error 9 -> CLIENT ERROR
Error 10 -> SERVER ERROR
Error 11 -> CONNECTION SOCKET CREATE FAILURE
Error 12 -> CONNECTION DATA EXISTS
Error 13 -> CONNECTION DATA DOES NOT EXIST
Error 14 -> NOT STORED
Error 15 -> STORED
Error 16 -> NOT FOUND
Error 17 -> MEMORY ALLOCATION FAILURE
Error 18 -> PARTIAL READ
Error 19 -> SOME ERRORS WERE REPORTED
Error 20 -> NO SERVERS DEFINED
Error 21 -> SERVER END
Error 22 -> SERVER DELETE
Error 23 -> SERVER VALUE
Error 24 -> STAT VALUE
Error 25 -> Gibberish returned!
Error 26 -> SYSTEM ERROR
Error 27 -> COULD NOT OPEN UNIX SOCKET
Error 28 -> ACTION NOT SUPPORTED
Error 29 -> A KEY LENGTH OF ZERO WAS PROVIDED
Error 30 -> FETCH WAS NOT COMPLETED
Error 31 -> A TIMEOUT OCCURRED
Error 32 -> ACTION QUEUED
Error 33 -> A BAD KEY WAS PROVIDED/CHARACTERS OUT OF RANGE
Error 34 -> THE HOST TRANSPORT PROTOCOL DOES NOT MATCH THAT OF THE CLIENT
Error 35 -> SERVER IS MARKED DEAD
Key foo
Error 0 -> SUCCESS
Error 1 -> FAILURE
Error 2 -> HOSTNAME LOOKUP FAILURE
Error 3 -> CONNECTION FAILURE
Error 4 -> CONNECTION BIND FAILURE
Error 5 -> WRITE FAILURE
Error 6 -> READ FAILURE
Error 7 -> UNKNOWN READ FAILURE
Error 8 -> PROTOCOL ERROR
Error 9 -> CLIENT ERROR
Error 10 -> SERVER ERROR
Error 11 -> CONNECTION SOCKET CREATE FAILURE
Error 12 -> CONNECTION DATA EXISTS
Error 13 -> CONNECTION DATA DOES NOT EXIST
Error 14 -> NOT STORED
Error 15 -> STORED
Error 16 -> NOT FOUND
Error 17 -> MEMORY ALLOCATION FAILURE
Error 18 -> PARTIAL READ
Error 19 -> SOME ERRORS WERE REPORTED
Error 20 -> NO SERVERS DEFINED
Error 21 -> SERVER END
Error 22 -> SERVER DELETE
Error 23 -> SERVER VALUE
Error 24 -> STAT VALUE
Error 25 -> Gibberish returned!
Error 26 -> SYSTEM ERROR
Error 27 -> COULD NOT OPEN UNIX SOCKET
Error 28 -> ACTION NOT SUPPORTED
Error 29 -> A KEY LENGTH OF ZERO WAS PROVIDED
Error 30 -> FETCH WAS NOT COMPLETED
Error 31 -> A TIMEOUT OCCURRED
Error 32 -> ACTION QUEUED
Error 33 -> A BAD KEY WAS PROVIDED/CHARACTERS OUT OF RANGE
Error 34 -> THE HOST TRANSPORT PROTOCOL DOES NOT MATCH THAT OF THE CLIENT
Error 35 -> SERVER IS MARKED DEAD
Error 0 -> SUCCESS
Error 1 -> FAILURE
Error 2 -> HOSTNAME LOOKUP FAILURE
Error 3 -> CONNECTION FAILURE
Error 4 -> CONNECTION BIND FAILURE
Error 5 -> WRITE FAILURE
Error 6 -> READ FAILURE
Error 7 -> UNKNOWN READ FAILURE
Error 8 -> PROTOCOL ERROR
Error 9 -> CLIENT ERROR
Error 10 -> SERVER ERROR
Error 11 -> CONNECTION SOCKET CREATE FAILURE
Error 12 -> CONNECTION DATA EXISTS
Error 13 -> CONNECTION DATA DOES NOT EXIST
Error 14 -> NOT STORED
Error 15 -> STORED
Error 16 -> NOT FOUND
Error 17 -> MEMORY ALLOCATION FAILURE
Error 18 -> PARTIAL READ
Error 19 -> SOME ERRORS WERE REPORTED
Error 20 -> NO SERVERS DEFINED
Error 21 -> SERVER END
Error 22 -> SERVER DELETE
Error 23 -> SERVER VALUE
Error 24 -> STAT VALUE
Error 25 -> Gibberish returned!
Error 26 -> SYSTEM ERROR
Error 27 -> COULD NOT OPEN UNIX SOCKET
Error 28 -> ACTION NOT SUPPORTED
Error 29 -> A KEY LENGTH OF ZERO WAS PROVIDED
Error 30 -> FETCH WAS NOT COMPLETED
Error 31 -> A TIMEOUT OCCURRED
Error 32 -> ACTION QUEUED
Error 33 -> A BAD KEY WAS PROVIDED/CHARACTERS OUT OF RANGE
Error 34 -> THE HOST TRANSPORT PROTOCOL DOES NOT MATCH THAT OF THE CLIENT
Error 35 -> SERVER IS MARKED DEAD
Key foo
Error 0 -> SUCCESS
Error 1 -> FAILURE
Error 2 -> HOSTNAME LOOKUP FAILURE
Error 3 -> CONNECTION FAILURE
Error 4 -> CONNECTION BIND FAILURE
Error 5 -> WRITE FAILURE
Error 6 -> READ FAILURE
Error 7 -> UNKNOWN READ FAILURE
Error 8 -> PROTOCOL ERROR
Error 9 -> CLIENT ERROR
Error 10 -> SERVER ERROR
Error 11 -> CONNECTION SOCKET CREATE FAILURE
Error 12 -> CONNECTION DATA EXISTS
Error 13 -> CONNECTION DATA DOES NOT EXIST
Error 14 -> NOT STORED
Error 15 -> STORED
Error 16 -> NOT FOUND
Error 17 -> MEMORY ALLOCATION FAILURE
Error 18 -> PARTIAL READ
Error 19 -> SOME ERRORS WERE REPORTED
Error 20 -> NO SERVERS DEFINED
Error 21 -> SERVER END
Error 22 -> SERVER DELETE
Error 23 -> SERVER VALUE
Error 24 -> STAT VALUE
Error 25 -> Gibberish returned!
Error 26 -> SYSTEM ERROR
Error 27 -> COULD NOT OPEN UNIX SOCKET
Error 28 -> ACTION NOT SUPPORTED
Error 29 -> A KEY LENGTH OF ZERO WAS PROVIDED
Error 30 -> FETCH WAS NOT COMPLETED
Error 31 -> A TIMEOUT OCCURRED
Error 32 -> ACTION QUEUED
Error 33 -> A BAD KEY WAS PROVIDED/CHARACTERS OUT OF RANGE
Error 34 -> THE HOST TRANSPORT PROTOCOL DOES NOT MATCH THAT OF THE CLIENT
Error 35 -> SERVER IS MARKED DEAD
Key foo
Error 0 -> SUCCESS
Error 1 -> FAILURE
Error 2 -> HOSTNAME LOOKUP FAILURE
Error 3 -> CONNECTION FAILURE
Error 4 -> CONNECTION BIND FAILURE
Error 5 -> WRITE FAILURE
Error 6 -> READ FAILURE
Error 7 -> UNKNOWN READ FAILURE
Error 8 -> PROTOCOL ERROR
Error 9 -> CLIENT ERROR
Error 10 -> SERVER ERROR
Error 11 -> CONNECTION SOCKET CREATE FAILURE
Error 12 -> CONNECTION DATA EXISTS
Error 13 -> CONNECTION DATA DOES NOT EXIST
Error 14 -> NOT STORED
Error 15 -> STORED
Error 16 -> NOT FOUND
Error 17 -> MEMORY ALLOCATION FAILURE
Error 18 -> PARTIAL READ
Error 19 -> SOME ERRORS WERE REPORTED
Error 20 -> NO SERVERS DEFINED
Error 21 -> SERVER END
Error 22 -> SERVER DELETE
Error 23 -> SERVER VALUE
Error 24 -> STAT VALUE
Error 25 -> Gibberish returned!
Error 26 -> SYSTEM ERROR
Error 27 -> COULD NOT OPEN UNIX SOCKET
Error 28 -> ACTION NOT SUPPORTED
Error 29 -> A KEY LENGTH OF ZERO WAS PROVIDED
Error 30 -> FETCH WAS NOT COMPLETED
Error 31 -> A TIMEOUT OCCURRED
Error 32 -> ACTION QUEUED
Error 33 -> A BAD KEY WAS PROVIDED/CHARACTERS OUT OF RANGE
Error 34 -> THE HOST TRANSPORT PROTOCOL DOES NOT MATCH THAT OF THE CLIENT
Error 35 -> SERVER IS MARKED DEAD
Key foo
Error 0 -> SUCCESS
Error 1 -> FAILURE
Error 2 -> HOSTNAME LOOKUP FAILURE
Error 3 -> CONNECTION FAILURE
Error 4 -> CONNECTION BIND FAILURE
Error 5 -> WRITE FAILURE
Error 6 -> READ FAILURE
Error 7 -> UNKNOWN READ FAILURE
Error 8 -> PROTOCOL ERROR
Error 9 -> CLIENT ERROR
Error 10 -> SERVER ERROR
Error 11 -> CONNECTION SOCKET CREATE FAILURE
Error 12 -> CONNECTION DATA EXISTS
Error 13 -> CONNECTION DATA DOES NOT EXIST
Error 14 -> NOT STORED
Error 15 -> STORED
Error 16 -> NOT FOUND
Error 17 -> MEMORY ALLOCATION FAILURE
Error 18 -> PARTIAL READ
Error 19 -> SOME ERRORS WERE REPORTED
Error 20 -> NO SERVERS DEFINED
Error 21 -> SERVER END
Error 22 -> SERVER DELETE
Error 23 -> SERVER VALUE
Error 24 -> STAT VALUE
Error 25 -> Gibberish returned!
Error 26 -> SYSTEM ERROR
Error 27 -> COULD NOT OPEN UNIX SOCKET
Error 28 -> ACTION NOT SUPPORTED
Error 29 -> A KEY LENGTH OF ZERO WAS PROVIDED
Error 30 -> FETCH WAS NOT COMPLETED
Error 31 -> A TIMEOUT OCCURRED
Error 32 -> ACTION QUEUED
Error 33 -> A BAD KEY WAS PROVIDED/CHARACTERS OUT OF RANGE
Error 34 -> THE HOST TRANSPORT PROTOCOL DOES NOT MATCH THAT OF THE CLIENT
Error 35 -> SERVER IS MARKED DEAD
Key foo
Error 0 -> SUCCESS
Error 1 -> FAILURE
Error 2 -> HOSTNAME LOOKUP FAILURE
Error 3 -> CONNECTION FAILURE
Error 4 -> CONNECTION BIND FAILURE
Error 5 -> WRITE FAILURE
Error 6 -> READ FAILURE
Error 7 -> UNKNOWN READ FAILURE
Error 8 -> PROTOCOL ERROR
Error 9 -> CLIENT ERROR
Error 10 -> SERVER ERROR
Error 11 -> CONNECTION SOCKET CREATE FAILURE
Error 12 -> CONNECTION DATA EXISTS
Error 13 -> CONNECTION DATA DOES NOT EXIST
Error 14 -> NOT STORED
Error 15 -> STORED
Error 16 -> NOT FOUND
Error 17 -> MEMORY ALLOCATION FAILURE
Error 18 -> PARTIAL READ
Error 19 -> SOME ERRORS WERE REPORTED
Error 20 -> NO SERVERS DEFINED
Error 21 -> SERVER END
Error 22 -> SERVER DELETE
Error 23 -> SERVER VALUE
Error 24 -> STAT VALUE
Error 25 -> Gibberish returned!
Error 26 -> SYSTEM ERROR
Error 27 -> COULD NOT OPEN UNIX SOCKET
Error 28 -> ACTION NOT SUPPORTED
Error 29 -> A KEY LENGTH OF ZERO WAS PROVIDED
Error 30 -> FETCH WAS NOT COMPLETED
Error 31 -> A TIMEOUT OCCURRED
Error 32 -> ACTION QUEUED
Error 33 -> A BAD KEY WAS PROVIDED/CHARACTERS OUT OF RANGE
Error 34 -> THE HOST TRANSPORT PROTOCOL DOES NOT MATCH THAT OF THE CLIENT
Error 35 -> SERVER IS MARKED DEAD
Key foo
Error 0 -> SUCCESS
Error 1 -> FAILURE
Error 2 -> HOSTNAME LOOKUP FAILURE
Error 3 -> CONNECTION FAILURE
Error 4 -> CONNECTION BIND FAILURE
Error 5 -> WRITE FAILURE
Error 6 -> READ FAILURE
Error 7 -> UNKNOWN READ FAILURE
Error 8 -> PROTOCOL ERROR
Error 9 -> CLIENT ERROR
Error 10 -> SERVER ERROR
Error 11 -> CONNECTION SOCKET CREATE FAILURE
Error 12 -> CONNECTION DATA EXISTS
Error 13 -> CONNECTION DATA DOES NOT EXIST
Error 14 -> NOT STORED
Error 15 -> STORED
Error 16 -> NOT FOUND
Error 17 -> MEMORY ALLOCATION FAILURE
Error 18 -> PARTIAL READ
Error 19 -> SOME ERRORS WERE REPORTED
Error 20 -> NO SERVERS DEFINED
Error 21 -> SERVER END
Error 22 -> SERVER DELETE
Error 23 -> SERVER VALUE
Error 24 -> STAT VALUE
Error 25 -> Gibberish returned!
Error 26 -> SYSTEM ERROR
Error 27 -> COULD NOT OPEN UNIX SOCKET
Error 28 -> ACTION NOT SUPPORTED
Error 29 -> A KEY LENGTH OF ZERO WAS PROVIDED
Error 30 -> FETCH WAS NOT COMPLETED
Error 31 -> A TIMEOUT OCCURRED
Error 32 -> ACTION QUEUED
Error 33 -> A BAD KEY WAS PROVIDED/CHARACTERS OUT OF RANGE
Error 34 -> THE HOST TRANSPORT PROTOCOL DOES NOT MATCH THAT OF THE CLIENT
Error 35 -> SERVER IS MARKED DEAD
Key foo
Error 0 -> SUCCESS
Error 1 -> FAILURE
Error 2 -> HOSTNAME LOOKUP FAILURE
Error 3 -> CONNECTION FAILURE
Error 4 -> CONNECTION BIND FAILURE
Error 5 -> WRITE FAILURE
Error 6 -> READ FAILURE
Error 7 -> UNKNOWN READ FAILURE
Error 8 -> PROTOCOL ERROR
Error 9 -> CLIENT ERROR
Error 10 -> SERVER ERROR
Error 11 -> CONNECTION SOCKET CREATE FAILURE
Error 12 -> CONNECTION DATA EXISTS
Error 13 -> CONNECTION DATA DOES NOT EXIST
Error 14 -> NOT STORED
Error 15 -> STORED
Error 16 -> NOT FOUND
Error 17 -> MEMORY ALLOCATION FAILURE
Error 18 -> PARTIAL READ
Error 19 -> SOME ERRORS WERE REPORTED
Error 20 -> NO SERVERS DEFINED
Error 21 -> SERVER END
Error 22 -> SERVER DELETE
Error 23 -> SERVER VALUE
Error 24 -> STAT VALUE
Error 25 -> Gibberish returned!
Error 26 -> SYSTEM ERROR
Error 27 -> COULD NOT OPEN UNIX SOCKET
Error 28 -> ACTION NOT SUPPORTED
Error 29 -> A KEY LENGTH OF ZERO WAS PROVIDED
Error 30 -> FETCH WAS NOT COMPLETED
Error 31 -> A TIMEOUT OCCURRED
Error 32 -> ACTION QUEUED
Error 33 -> A BAD KEY WAS PROVIDED/CHARACTERS OUT OF RANGE
Error 34 -> THE HOST TRANSPORT PROTOCOL DOES NOT MATCH THAT OF THE CLIENT
Error 35 -> SERVER IS MARKED DEAD
Key foo
Error 0 -> SUCCESS
Error 1 -> FAILURE
Error 2 -> HOSTNAME LOOKUP FAILURE
Error 3 -> CONNECTION FAILURE
Error 4 -> CONNECTION BIND FAILURE
Error 5 -> WRITE FAILURE
Error 6 -> READ FAILURE
Error 7 -> UNKNOWN READ FAILURE
Error 8 -> PROTOCOL ERROR
Error 9 -> CLIENT ERROR
Error 10 -> SERVER ERROR
Error 11 -> CONNECTION SOCKET CREATE FAILURE
Error 12 -> CONNECTION DATA EXISTS
Error 13 -> CONNECTION DATA DOES NOT EXIST
Error 14 -> NOT STORED
Error 15 -> STORED
Error 16 -> NOT FOUND
Error 17 -> MEMORY ALLOCATION FAILURE
Error 18 -> PARTIAL READ
Error 19 -> SOME ERRORS WERE REPORTED
Error 20 -> NO SERVERS DEFINED
Error 21 -> SERVER END
Error 22 -> SERVER DELETE
Error 23 -> SERVER VALUE
Error 24 -> STAT VALUE
Error 25 -> Gibberish returned!
Error 26 -> SYSTEM ERROR
Error 27 -> COULD NOT OPEN UNIX SOCKET
Error 28 -> ACTION NOT SUPPORTED
Error 29 -> A KEY LENGTH OF ZERO WAS PROVIDED
Error 30 -> FETCH WAS NOT COMPLETED
Error 31 -> A TIMEOUT OCCURRED
Error 32 -> ACTION QUEUED
Error 33 -> A BAD KEY WAS PROVIDED/CHARACTERS OUT OF RANGE
Error 34 -> THE HOST TRANSPORT PROTOCOL DOES NOT MATCH THAT OF THE CLIENT
Error 35 -> SERVER IS MARKED DEAD
Key foo
Error 0 -> SUCCESS
Error 1 -> FAILURE
Error 2 -> HOSTNAME LOOKUP FAILURE
Error 3 -> CONNECTION FAILURE
Error 4 -> CONNECTION BIND FAILURE
Error 5 -> WRITE FAILURE
Error 6 -> READ FAILURE
Error 7 -> UNKNOWN READ FAILURE
Error 8 -> PROTOCOL ERROR
Error 9 -> CLIENT ERROR
Error 10 -> SERVER ERROR
Error 11 -> CONNECTION SOCKET CREATE FAILURE
Error 12 -> CONNECTION DATA EXISTS
Error 13 -> CONNECTION DATA DOES NOT EXIST
Error 14 -> NOT STORED
Error 15 -> STORED
Error 16 -> NOT FOUND
Error 17 -> MEMORY ALLOCATION FAILURE
Error 18 -> PARTIAL READ
Error 19 -> SOME ERRORS WERE REPORTED
Error 20 -> NO SERVERS DEFINED
Error 21 -> SERVER END
Error 22 -> SERVER DELETE
Error 23 -> SERVER VALUE
Error 24 -> STAT VALUE
Error 25 -> Gibberish returned!
Error 26 -> SYSTEM ERROR
Error 27 -> COULD NOT OPEN UNIX SOCKET
Error 28 -> ACTION NOT SUPPORTED
Error 29 -> A KEY LENGTH OF ZERO WAS PROVIDED
Error 30 -> FETCH WAS NOT COMPLETED
Error 31 -> A TIMEOUT OCCURRED
Error 32 -> ACTION QUEUED
Error 33 -> A BAD KEY WAS PROVIDED/CHARACTERS OUT OF RANGE
Error 34 -> THE HOST TRANSPORT PROTOCOL DOES NOT MATCH THAT OF THE CLIENT
Error 35 -> SERVER IS MARKED DEAD
Key foo
Error 0 -> SUCCESS
Error 1 -> FAILURE
Error 2 -> HOSTNAME LOOKUP FAILURE
Error 3 -> CONNECTION FAILURE
Error 4 -> CONNECTION BIND FAILURE
Error 5 -> WRITE FAILURE
Error 6 -> READ FAILURE
Error 7 -> UNKNOWN READ FAILURE
Error 8 -> PROTOCOL ERROR
Error 9 -> CLIENT ERROR
Error 10 -> SERVER ERROR
Error 11 -> CONNECTION SOCKET CREATE FAILURE
Error 12 -> CONNECTION DATA EXISTS
Error 13 -> CONNECTION DATA DOES NOT EXIST
Error 14 -> NOT STORED
Error 15 -> STORED
Error 16 -> NOT FOUND
Error 17 -> MEMORY ALLOCATION FAILURE
Error 18 -> PARTIAL READ
Error 19 -> SOME ERRORS WERE REPORTED
Error 20 -> NO SERVERS DEFINED
Error 21 -> SERVER END
Error 22 -> SERVER DELETE
Error 23 -> SERVER VALUE
Error 24 -> STAT VALUE
Error 25 -> Gibberish returned!
Error 26 -> SYSTEM ERROR
Error 27 -> COULD NOT OPEN UNIX SOCKET
Error 28 -> ACTION NOT SUPPORTED
Error 29 -> A KEY LENGTH OF ZERO WAS PROVIDED
Error 30 -> FETCH WAS NOT COMPLETED
Error 31 -> A TIMEOUT OCCURRED
Error 32 -> ACTION QUEUED
Error 33 -> A BAD KEY WAS PROVIDED/CHARACTERS OUT OF RANGE
Error 34 -> THE HOST TRANSPORT PROTOCOL DOES NOT MATCH THAT OF THE CLIENT
Error 35 -> SERVER IS MARKED DEAD
Key foo
Error 0 -> SUCCESS
Error 1 -> FAILURE
Error 2 -> HOSTNAME LOOKUP FAILURE
Error 3 -> CONNECTION FAILURE
Error 4 -> CONNECTION BIND FAILURE
Error 5 -> WRITE FAILURE
Error 6 -> READ FAILURE
Error 7 -> UNKNOWN READ FAILURE
Error 8 -> PROTOCOL ERROR
Error 9 -> CLIENT ERROR
Error 10 -> SERVER ERROR
Error 11 -> CONNECTION SOCKET CREATE FAILURE
Error 12 -> CONNECTION DATA EXISTS
Error 13 -> CONNECTION DATA DOES NOT EXIST
Error 14 -> NOT STORED
Error 15 -> STORED
Error 16 -> NOT FOUND
Error 17 -> MEMORY ALLOCATION FAILURE
Error 18 -> PARTIAL READ
Error 19 -> SOME ERRORS WERE REPORTED
Error 20 -> NO SERVERS DEFINED
Error 21 -> SERVER END
Error 22 -> SERVER DELETE
Error 23 -> SERVER VALUE
Error 24 -> STAT VALUE
Error 25 -> Gibberish returned!
Error 26 -> SYSTEM ERROR
Error 27 -> COULD NOT OPEN UNIX SOCKET
Error 28 -> ACTION NOT SUPPORTED
Error 29 -> A KEY LENGTH OF ZERO WAS PROVIDED
Error 30 -> FETCH WAS NOT COMPLETED
Error 31 -> A TIMEOUT OCCURRED
Error 32 -> ACTION QUEUED
Error 33 -> A BAD KEY WAS PROVIDED/CHARACTERS OUT OF RANGE
Error 34 -> THE HOST TRANSPORT PROTOCOL DOES NOT MATCH THAT OF THE CLIENT
Error 35 -> SERVER IS MARKED DEAD
Key foo
ketama_weighted:10.0.1.1|11211|600|176
ketama_weighted:10.0.1.2|11211|300|88
ketama_weighted:10.0.1.3|11211|200|56
ketama_weighted:10.0.1.4|11211|350|104
ketama_weighted:10.0.1.5|11211|1000|296
ketama_weighted:10.0.1.6|11211|800|236
ketama_weighted:10.0.1.7|11211|950|280
ketama_weighted:10.0.1.8|11211|100|28
ketama_weighted:10.0.1.1|11211|600|160
ketama_weighted:10.0.1.2|11211|300|80
ketama_weighted:10.0.1.4|11211|350|92
ketama_weighted:10.0.1.5|11211|1000|272
ketama_weighted:10.0.1.6|11211|800|216
ketama_weighted:10.0.1.7|11211|950|256
ketama_weighted:10.0.1.8|11211|100|24
ketama_weighted:10.0.1.1|11211|600|176
ketama_weighted:10.0.1.2|11211|300|88
ketama_weighted:10.0.1.3|11211|200|56
ketama_weighted:10.0.1.4|11211|350|104
ketama_weighted:10.0.1.5|11211|1000|296
ketama_weighted:10.0.1.6|11211|800|236
ketama_weighted:10.0.1.7|11211|950|280
ketama_weighted:10.0.1.8|11211|100|28
Error 0 -> SUCCESS
Error 1 -> FAILURE
Error 2 -> HOSTNAME LOOKUP FAILURE
Error 3 -> CONNECTION FAILURE
Error 4 -> CONNECTION BIND FAILURE
Error 5 -> WRITE FAILURE
Error 6 -> READ FAILURE
Error 7 -> UNKNOWN READ FAILURE
Error 8 -> PROTOCOL ERROR
Error 9 -> CLIENT ERROR
Error 10 -> SERVER ERROR
Error 11 -> CONNECTION SOCKET CREATE FAILURE
Error 12 -> CONNECTION DATA EXISTS
Error 13 -> CONNECTION DATA DOES NOT EXIST
Error 14 -> NOT STORED
Error 15 -> STORED
Error 16 -> NOT FOUND
Error 17 -> MEMORY ALLOCATION FAILURE
Error 18 -> PARTIAL READ
Error 19 -> SOME ERRORS WERE REPORTED
Error 20 -> NO SERVERS DEFINED
Error 21 -> SERVER END
Error 22 -> SERVER DELETE
Error 23 -> SERVER VALUE
Error 24 -> STAT VALUE
Error 25 -> Gibberish returned!
Error 26 -> SYSTEM ERROR
Error 27 -> COULD NOT OPEN UNIX SOCKET
Error 28 -> ACTION NOT SUPPORTED
Error 29 -> A KEY LENGTH OF ZERO WAS PROVIDED
Error 30 -> FETCH WAS NOT COMPLETED
Error 31 -> A TIMEOUT OCCURRED
Error 32 -> ACTION QUEUED
Error 33 -> A BAD KEY WAS PROVIDED/CHARACTERS OUT OF RANGE
Error 34 -> THE HOST TRANSPORT PROTOCOL DOES NOT MATCH THAT OF THE CLIENT
Error 35 -> SERVER IS MARKED DEAD
Key foo
Error 0 -> SUCCESS
Error 1 -> FAILURE
Error 2 -> HOSTNAME LOOKUP FAILURE
Error 3 -> CONNECTION FAILURE
Error 4 -> CONNECTION BIND FAILURE
Error 5 -> WRITE FAILURE
Error 6 -> READ FAILURE
Error 7 -> UNKNOWN READ FAILURE
Error 8 -> PROTOCOL ERROR
Error 9 -> CLIENT ERROR
Error 10 -> SERVER ERROR
Error 11 -> CONNECTION SOCKET CREATE FAILURE
Error 12 -> CONNECTION DATA EXISTS
Error 13 -> CONNECTION DATA DOES NOT EXIST
Error 14 -> NOT STORED
Error 15 -> STORED
Error 16 -> NOT FOUND
Error 17 -> MEMORY ALLOCATION FAILURE
Error 18 -> PARTIAL READ
Error 19 -> SOME ERRORS WERE REPORTED
Error 20 -> NO SERVERS DEFINED
Error 21 -> SERVER END
Error 22 -> SERVER DELETE
Error 23 -> SERVER VALUE
Error 24 -> STAT VALUE
Error 25 -> Gibberish returned!
Error 26 -> SYSTEM ERROR
Error 27 -> COULD NOT OPEN UNIX SOCKET
Error 28 -> ACTION NOT SUPPORTED
Error 29 -> A KEY LENGTH OF ZERO WAS PROVIDED
Error 30 -> FETCH WAS NOT COMPLETED
Error 31 -> A TIMEOUT OCCURRED
Error 32 -> ACTION QUEUED
Error 33 -> A BAD KEY WAS PROVIDED/CHARACTERS OUT OF RANGE
Error 34 -> THE HOST TRANSPORT PROTOCOL DOES NOT MATCH THAT OF THE CLIENT
Error 35 -> SERVER IS MARKED DEAD
Key foo
Error 0 -> SUCCESS
Error 1 -> FAILURE
Error 2 -> HOSTNAME LOOKUP FAILURE
Error 3 -> CONNECTION FAILURE
Error 4 -> CONNECTION BIND FAILURE
Error 5 -> WRITE FAILURE
Error 6 -> READ FAILURE
Error 7 -> UNKNOWN READ FAILURE
Error 8 -> PROTOCOL ERROR
Error 9 -> CLIENT ERROR
Error 10 -> SERVER ERROR
Error 11 -> CONNECTION SOCKET CREATE FAILURE
Error 12 -> CONNECTION DATA EXISTS
Error 13 -> CONNECTION DATA DOES NOT EXIST
Error 14 -> NOT STORED
Error 15 -> STORED
Error 16 -> NOT FOUND
Error 17 -> MEMORY ALLOCATION FAILURE
Error 18 -> PARTIAL READ
Error 19 -> SOME ERRORS WERE REPORTED
Error 20 -> NO SERVERS DEFINED
Error 21 -> SERVER END
Error 22 -> SERVER DELETE
Error 23 -> SERVER VALUE
Error 24 -> STAT VALUE
Error 25 -> Gibberish returned!
Error 26 -> SYSTEM ERROR
Error 27 -> COULD NOT OPEN UNIX SOCKET
Error 28 -> ACTION NOT SUPPORTED
Error 29 -> A KEY LENGTH OF ZERO WAS PROVIDED
Error 30 -> FETCH WAS NOT COMPLETED
Error 31 -> A TIMEOUT OCCURRED
Error 32 -> ACTION QUEUED
Error 33 -> A BAD KEY WAS PROVIDED/CHARACTERS OUT OF RANGE
Error 34 -> THE HOST TRANSPORT PROTOCOL DOES NOT MATCH THAT OF THE CLIENT
Error 35 -> SERVER IS MARKED DEAD
Key foo
Error 0 -> SUCCESS
Error 1 -> FAILURE
Error 2 -> HOSTNAME LOOKUP FAILURE
Error 3 -> CONNECTION FAILURE
Error 4 -> CONNECTION BIND FAILURE
Error 5 -> WRITE FAILURE
Error 6 -> READ FAILURE
Error 7 -> UNKNOWN READ FAILURE
Error 8 -> PROTOCOL ERROR
Error 9 -> CLIENT ERROR
Error 10 -> SERVER ERROR
Error 11 -> CONNECTION SOCKET CREATE FAILURE
Error 12 -> CONNECTION DATA EXISTS
Error 13 -> CONNECTION DATA DOES NOT EXIST
Error 14 -> NOT STORED
Error 15 -> STORED
Error 16 -> NOT FOUND
Error 17 -> MEMORY ALLOCATION FAILURE
Error 18 -> PARTIAL READ
Error 19 -> SOME ERRORS WERE REPORTED
Error 20 -> NO SERVERS DEFINED
Error 21 -> SERVER END
Error 22 -> SERVER DELETE
Error 23 -> SERVER VALUE
Error 24 -> STAT VALUE
Error 25 -> Gibberish returned!
Error 26 -> SYSTEM ERROR
Error 27 -> COULD NOT OPEN UNIX SOCKET
Error 28 -> ACTION NOT SUPPORTED
Error 29 -> A KEY LENGTH OF ZERO WAS PROVIDED
Error 30 -> FETCH WAS NOT COMPLETED
Error 31 -> A TIMEOUT OCCURRED
Error 32 -> ACTION QUEUED
Error 33 -> A BAD KEY WAS PROVIDED/CHARACTERS OUT OF RANGE
Error 34 -> THE HOST TRANSPORT PROTOCOL DOES NOT MATCH THAT OF THE CLIENT
Error 35 -> SERVER IS MARKED DEAD
Key foo
Error 0 -> SUCCESS
Error 1 -> FAILURE
Error 2 -> HOSTNAME LOOKUP FAILURE
Error 3 -> CONNECTION FAILURE
Error 4 -> CONNECTION BIND FAILURE
Error 5 -> WRITE FAILURE
Error 6 -> READ FAILURE
Error 7 -> UNKNOWN READ FAILURE
Error 8 -> PROTOCOL ERROR
Error 9 -> CLIENT ERROR
Error 10 -> SERVER ERROR
Error 11 -> CONNECTION SOCKET CREATE FAILURE
Error 12 -> CONNECTION DATA EXISTS
Error 13 -> CONNECTION DATA DOES NOT EXIST
Error 14 -> NOT STORED
Error 15 -> STORED
Error 16 -> NOT FOUND
Error 17 -> MEMORY ALLOCATION FAILURE
Error 18 -> PARTIAL READ
Error 19 -> SOME ERRORS WERE REPORTED
Error 20 -> NO SERVERS DEFINED
Error 21 -> SERVER END
Error 22 -> SERVER DELETE
Error 23 -> SERVER VALUE
Error 24 -> STAT VALUE
Error 25 -> Gibberish returned!
Error 26 -> SYSTEM ERROR
Error 27 -> COULD NOT OPEN UNIX SOCKET
Error 28 -> ACTION NOT SUPPORTED
Error 29 -> A KEY LENGTH OF ZERO WAS PROVIDED
Error 30 -> FETCH WAS NOT COMPLETED
Error 31 -> A TIMEOUT OCCURRED
Error 32 -> ACTION QUEUED
Error 33 -> A BAD KEY WAS PROVIDED/CHARACTERS OUT OF RANGE
Error 34 -> THE HOST TRANSPORT PROTOCOL DOES NOT MATCH THAT OF THE CLIENT
Error 35 -> SERVER IS MARKED DEAD
Key Thisismorethentheallottednumberofcharactersfoo
ketama_weighted:10.0.1.1|11211|600|176
ketama_weighted:10.0.1.2|11211|300|88
ketama_weighted:10.0.1.3|11211|200|56
ketama_weighted:10.0.1.4|11211|350|104
ketama_weighted:10.0.1.5|11211|1000|296
ketama_weighted:10.0.1.6|11211|800|236
ketama_weighted:10.0.1.7|11211|950|280
ketama_weighted:10.0.1.8|11211|100|28
ketama_weighted:localhost|11221|1|160
ketama_weighted:localhost|11222|1|160
ketama_weighted:localhost|11223|1|160
ketama_weighted:localhost|11224|1|160
ketama_weighted:localhost|11225|1|160
ketama_weighted:localhost|11221|1|160
ketama_weighted:localhost|11222|1|160
ketama_weighted:localhost|11223|1|160
ketama_weighted:localhost|11224|1|160
ketama_weighted:localhost|11225|1|160
ketama_weighted:localhost|11221|1|160
ketama_weighted:localhost|11222|1|160
ketama_weighted:localhost|11223|1|160
ketama_weighted:localhost|11224|1|160
ketama_weighted:localhost|11225|1|160
ketama_weighted:localhost|11221|1|160
ketama_weighted:localhost|11222|1|160
ketama_weighted:localhost|11223|1|160
ketama_weighted:localhost|11224|1|160
ketama_weighted:localhost|11225|1|160

server 0|localhost|11221 bytes: 3257982

server 1|localhost|11222 bytes: 3099222

server 2|localhost|11223 bytes: 3503809

server 3|localhost|11224 bytes: 3780740

server 4|localhost|11225 bytes: 3124164
ketama_weighted:localhost|11221|1|160
ketama_weighted:localhost|11222|1|160
ketama_weighted:localhost|11223|1|160
ketama_weighted:localhost|11224|1|160
ketama_weighted:localhost|11225|1|160
ketama_weighted:localhost|11221|1|160
ketama_weighted:localhost|11222|1|160
ketama_weighted:localhost|11223|1|160
ketama_weighted:localhost|11224|1|160
ketama_weighted:localhost|11225|1|160
ketama_weighted:localhost|11221|1|160
ketama_weighted:localhost|11222|1|160
ketama_weighted:localhost|11223|1|160
ketama_weighted:localhost|11224|1|160
ketama_weighted:localhost|11225|1|160
ketama_weighted:localhost|11221|1|160
ketama_weighted:localhost|11222|1|160
ketama_weighted:localhost|11223|1|160
ketama_weighted:localhost|11224|1|160
ketama_weighted:localhost|11225|1|160
ketama_weighted:localhost|11221|1|160
ketama_weighted:localhost|11222|1|160
ketama_weighted:localhost|11223|1|160
ketama_weighted:localhost|11224|1|160
ketama_weighted:localhost|11225|1|160
ketama_weighted:localhost|6666|1|160
ketama_weighted:localhost|11221|1|160
ketama_weighted:localhost|11222|1|160
ketama_weighted:localhost|11223|1|160
ketama_weighted:localhost|11224|1|160
ketama_weighted:localhost|11225|1|160
ketama_weighted:localhost|11221|1|160
ketama_weighted:localhost|11222|1|160
ketama_weighted:localhost|11223|1|160
ketama_weighted:localhost|11224|1|160
ketama_weighted:localhost|11225|1|160
