servers localhost:11221,localhost:11222,localhost:11223,localhost:11224,localhost:11225,
	localhost : 11221
	localhost : 11222
	localhost : 11223
	localhost : 11224
	localhost : 11225

Error 0 -> SUCCESS
Error 1 -> FAILURE
Error 2 -> HOSTNAME LOOKUP FAILURE
Error 3 -> CONNECTION FAILURE
Error 4 -> CONNECTION BIND FAILURE
Error 5 -> WRITE FAILURE
Error 6 -> READ FAILURE
Error 7 -> UNKNOWN READ FAILURE
Error 8 -> PROTOCOL ERROR
Error 9 -> CLIENT ERROR
Error 10 -> SERVER ERROR
Error 11 -> CONNECTION SOCKET CREATE FAILURE
Error 12 -> CONNECTION DATA EXISTS
Error 13 -> CONNECTION DATA DOES NOT EXIST
Error 14 -> NOT STORED
Error 15 -> STORED
Error 16 -> NOT FOUND
Error 17 -> MEMORY ALLOCATION FAILURE
Error 18 -> PARTIAL READ
Error 19 -> SOME ERRORS WERE REPORTED
Error 20 -> NO SERVERS DEFINED
Error 21 -> SERVER END
Error 22 -> SERVER DELETE
Error 23 -> SERVER VALUE
Error 24 -> STAT VALUE
Error 25 -> Gibberish returned!
Error 26 -> SYSTEM ERROR
Error 27 -> COULD NOT OPEN UNIX SOCKET
Error 28 -> ACTION NOT SUPPORTED
Error 29 -> A KEY LENGTH OF ZERO WAS PROVIDED
Error 30 -> FETCH WAS NOT COMPLETED
Error 31 -> A TIMEOUT OCCURRED
Error 32 -> ACTION QUEUED
Error 33 -> A BAD KEY WAS PROVIDED/CHARACTERS OUT OF RANGE
Error 34 -> THE HOST TRANSPORT PROTOCOL DOES NOT MATCH THAT OF THE CLIENT
Error 35 -> SERVER IS MARKED DEAD
Error 36 -> ENCOUNTERED AN UNKNOWN STAT KEY
Error 0 -> SUCCESS
Error 1 -> FAILURE
Error 2 -> HOSTNAME LOOKUP FAILURE
Error 3 -> CONNECTION FAILURE
Error 4 -> CONNECTION BIND FAILURE
Error 5 -> WRITE FAILURE
Error 6 -> READ FAILURE
Error 7 -> UNKNOWN READ FAILURE
Error 8 -> PROTOCOL ERROR
Error 9 -> CLIENT ERROR
Error 10 -> SERVER ERROR
Error 11 -> CONNECTION SOCKET CREATE FAILURE
Error 12 -> CONNECTION DATA EXISTS
Error 13 -> CONNECTION DATA DOES NOT EXIST
Error 14 -> NOT STORED
Error 15 -> STORED
Error 16 -> NOT FOUND
Error 17 -> MEMORY ALLOCATION FAILURE
Error 18 -> PARTIAL READ
Error 19 -> SOME ERRORS WERE REPORTED
Error 20 -> NO SERVERS DEFINED
Error 21 -> SERVER END
Error 22 -> SERVER DELETE
Error 23 -> SERVER VALUE
Error 24 -> STAT VALUE
Error 25 -> Gibberish returned!
Error 26 -> SYSTEM ERROR
Error 27 -> COULD NOT OPEN UNIX SOCKET
Error 28 -> ACTION NOT SUPPORTED
Error 29 -> A KEY LENGTH OF ZERO WAS PROVIDED
Error 30 -> FETCH WAS NOT COMPLETED
Error 31 -> A TIMEOUT OCCURRED
Error 32 -> ACTION QUEUED
Error 33 -> A BAD KEY WAS PROVIDED/CHARACTERS OUT OF RANGE
Error 34 -> THE HOST TRANSPORT PROTOCOL DOES NOT MATCH THAT OF THE CLIENT
Error 35 -> SERVER IS MARKED DEAD
Error 36 -> ENCOUNTERED AN UNKNOWN STAT KEY
Error 0 -> SUCCESS
Error 1 -> FAILURE
Error 2 -> HOSTNAME LOOKUP FAILURE
Error 3 -> CONNECTION FAILURE
Error 4 -> CONNECTION BIND FAILURE
Error 5 -> WRITE FAILURE
Error 6 -> READ FAILURE
Error 7 -> UNKNOWN READ FAILURE
Error 8 -> PROTOCOL ERROR
Error 9 -> CLIENT ERROR
Error 10 -> SERVER ERROR
Error 11 -> CONNECTION SOCKET CREATE FAILURE
Error 12 -> CONNECTION DATA EXISTS
Error 13 -> CONNECTION DATA DOES NOT EXIST
Error 14 -> NOT STORED
Error 15 -> STORED
Error 16 -> NOT FOUND
Error 17 -> MEMORY ALLOCATION FAILURE
Error 18 -> PARTIAL READ
Error 19 -> SOME ERRORS WERE REPORTED
Error 20 -> NO SERVERS DEFINED
Error 21 -> SERVER END
Error 22 -> SERVER DELETE
Error 23 -> SERVER VALUE
Error 24 -> STAT VALUE
Error 25 -> Gibberish returned!
Error 26 -> SYSTEM ERROR
Error 27 -> COULD NOT OPEN UNIX SOCKET
Error 28 -> ACTION NOT SUPPORTED
Error 29 -> A KEY LENGTH OF ZERO WAS PROVIDED
Error 30 -> FETCH WAS NOT COMPLETED
Error 31 -> A TIMEOUT OCCURRED
Error 32 -> ACTION QUEUED
Error 33 -> A BAD KEY WAS PROVIDED/CHARACTERS OUT OF RANGE
Error 34 -> THE HOST TRANSPORT PROTOCOL DOES NOT MATCH THAT OF THE CLIENT
Error 35 -> SERVER IS MARKED DEAD
Error 36 -> ENCOUNTERED AN UNKNOWN STAT KEY
Error 0 -> SUCCESS
Error 1 -> FAILURE
Error 2 -> HOSTNAME LOOKUP FAILURE
Error 3 -> CONNECTION FAILURE
Error 4 -> CONNECTION BIND FAILURE
Error 5 -> WRITE FAILURE
Error 6 -> READ FAILURE
Error 7 -> UNKNOWN READ FAILURE
Error 8 -> PROTOCOL ERROR
Error 9 -> CLIENT ERROR
Error 10 -> SERVER ERROR
Error 11 -> CONNECTION SOCKET CREATE FAILURE
Error 12 -> CONNECTION DATA EXISTS
Error 13 -> CONNECTION DATA DOES NOT EXIST
Error 14 -> NOT STORED
Error 15 -> STORED
Error 16 -> NOT FOUND
Error 17 -> MEMORY ALLOCATION FAILURE
Error 18 -> PARTIAL READ
Error 19 -> SOME ERRORS WERE REPORTED
Error 20 -> NO SERVERS DEFINED
Error 21 -> SERVER END
Error 22 -> SERVER DELETE
Error 23 -> SERVER VALUE
Error 24 -> STAT VALUE
Error 25 -> Gibberish returned!
Error 26 -> SYSTEM ERROR
Error 27 -> COULD NOT OPEN UNIX SOCKET
Error 28 -> ACTION NOT SUPPORTED
Error 29 -> A KEY LENGTH OF ZERO WAS PROVIDED
Error 30 -> FETCH WAS NOT COMPLETED
Error 31 -> A TIMEOUT OCCURRED
Error 32 -> ACTION QUEUED
Error 33 -> A BAD KEY WAS PROVIDED/CHARACTERS OUT OF RANGE
Error 34 -> THE HOST TRANSPORT PROTOCOL DOES NOT MATCH THAT OF THE CLIENT
Error 35 -> SERVER IS MARKED DEAD
Error 36 -> ENCOUNTERED AN UNKNOWN STAT KEY
Error 0 -> SUCCESS
Error 1 -> FAILURE
Error 2 -> HOSTNAME LOOKUP FAILURE
Error 3 -> CONNECTION FAILURE
Error 4 -> CONNECTION BIND FAILURE
Error 5 -> WRITE FAILURE
Error 6 -> READ FAILURE
Error 7 -> UNKNOWN READ FAILURE
Error 8 -> PROTOCOL ERROR
Error 9 -> CLIENT ERROR
Error 10 -> SERVER ERROR
Error 11 -> CONNECTION SOCKET CREATE FAILURE
Error 12 -> CONNECTION DATA EXISTS
Error 13 -> CONNECTION DATA DOES NOT EXIST
Error 14 -> NOT STORED
Error 15 -> STORED
Error 16 -> NOT FOUND
Error 17 -> MEMORY ALLOCATION FAILURE
Error 18 -> PARTIAL READ
Error 19 -> SOME ERRORS WERE REPORTED
Error 20 -> NO SERVERS DEFINED
Error 21 -> SERVER END
Error 22 -> SERVER DELETE
Error 23 -> SERVER VALUE
Error 24 -> STAT VALUE
Error 25 -> Gibberish returned!
Error 26 -> SYSTEM ERROR
Error 27 -> COULD NOT OPEN UNIX SOCKET
Error 28 -> ACTION NOT SUPPORTED
Error 29 -> A KEY LENGTH OF ZERO WAS PROVIDED
Error 30 -> FETCH WAS NOT COMPLETED
Error 31 -> A TIMEOUT OCCURRED
Error 32 -> ACTION QUEUED
Error 33 -> A BAD KEY WAS PROVIDED/CHARACTERS OUT OF RANGE
Error 34 -> THE HOST TRANSPORT PROTOCOL DOES NOT MATCH THAT OF THE CLIENT
Error 35 -> SERVER IS MARKED DEAD
Error 36 -> ENCOUNTERED AN UNKNOWN STAT KEY
Error 0 -> SUCCESS
Error 1 -> FAILURE
Error 2 -> HOSTNAME LOOKUP FAILURE
Error 3 -> CONNECTION FAILURE
Error 4 -> CONNECTION BIND FAILURE
Error 5 -> WRITE FAILURE
Error 6 -> READ FAILURE
Error 7 -> UNKNOWN READ FAILURE
Error 8 -> PROTOCOL ERROR
Error 9 -> CLIENT ERROR
Error 10 -> SERVER ERROR
Error 11 -> CONNECTION SOCKET CREATE FAILURE
Error 12 -> CONNECTION DATA EXISTS
Error 13 -> CONNECTION DATA DOES NOT EXIST
Error 14 -> NOT STORED
Error 15 -> STORED
Error 16 -> NOT FOUND
Error 17 -> MEMORY ALLOCATION FAILURE
Error 18 -> PARTIAL READ
Error 19 -> SOME ERRORS WERE REPORTED
Error 20 -> NO SERVERS DEFINED
Error 21 -> SERVER END
Error 22 -> SERVER DELETE
Error 23 -> SERVER VALUE
Error 24 -> STAT VALUE
Error 25 -> Gibberish returned!
Error 26 -> SYSTEM ERROR
Error 27 -> COULD NOT OPEN UNIX SOCKET
Error 28 -> ACTION NOT SUPPORTED
Error 29 -> A KEY LENGTH OF ZERO WAS PROVIDED
Error 30 -> FETCH WAS NOT COMPLETED
Error 31 -> A TIMEOUT OCCURRED
Error 32 -> ACTION QUEUED
Error 33 -> A BAD KEY WAS PROVIDED/CHARACTERS OUT OF RANGE
Error 34 -> THE HOST TRANSPORT PROTOCOL DOES NOT MATCH THAT OF THE CLIENT
Error 35 -> SERVER IS MARKED DEAD
Error 36 -> ENCOUNTERED AN UNKNOWN STAT KEY
Error 0 -> SUCCESS
Error 1 -> FAILURE
Error 2 -> HOSTNAME LOOKUP FAILURE
Error 3 -> CONNECTION FAILURE
Error 4 -> CONNECTION BIND FAILURE
Error 5 -> WRITE FAILURE
Error 6 -> READ FAILURE
Error 7 -> UNKNOWN READ FAILURE
Error 8 -> PROTOCOL ERROR
Error 9 -> CLIENT ERROR
Error 10 -> SERVER ERROR
Error 11 -> CONNECTION SOCKET CREATE FAILURE
Error 12 -> CONNECTION DATA EXISTS
Error 13 -> CONNECTION DATA DOES NOT EXIST
Error 14 -> NOT STORED
Error 15 -> STORED
Error 16 -> NOT FOUND
Error 17 -> MEMORY ALLOCATION FAILURE
Error 18 -> PARTIAL READ
Error 19 -> SOME ERRORS WERE REPORTED
Error 20 -> NO SERVERS DEFINED
Error 21 -> SERVER END
Error 22 -> SERVER DELETE
Error 23 -> SERVER VALUE
Error 24 -> STAT VALUE
Error 25 -> Gibberish returned!
Error 26 -> SYSTEM ERROR
Error 27 -> COULD NOT OPEN UNIX SOCKET
Error 28 -> ACTION NOT SUPPORTED
Error 29 -> A KEY LENGTH OF ZERO WAS PROVIDED
Error 30 -> FETCH WAS NOT COMPLETED
Error 31 -> A TIMEOUT OCCURRED
Error 32 -> ACTION QUEUED
Error 33 -> A BAD KEY WAS PROVIDED/CHARACTERS OUT OF RANGE
Error 34 -> THE HOST TRANSPORT PROTOCOL DOES NOT MATCH THAT OF THE CLIENT
Error 35 -> SERVER IS MARKED DEAD
Error 36 -> ENCOUNTERED AN UNKNOWN STAT KEY
Error 0 -> SUCCESS
Error 1 -> FAILURE
Error 2 -> HOSTNAME LOOKUP FAILURE
Error 3 -> CONNECTION FAILURE
Error 4 -> CONNECTION BIND FAILURE
Error 5 -> WRITE FAILURE
Error 6 -> READ FAILURE
Error 7 -> UNKNOWN READ FAILURE
Error 8 -> PROTOCOL ERROR
Error 9 -> CLIENT ERROR
Error 10 -> SERVER ERROR
Error 11 -> CONNECTION SOCKET CREATE FAILURE
Error 12 -> CONNECTION DATA EXISTS
Error 13 -> CONNECTION DATA DOES NOT EXIST
Error 14 -> NOT STORED
Error 15 -> STORED
Error 16 -> NOT FOUND
Error 17 -> MEMORY ALLOCATION FAILURE
Error 18 -> PARTIAL READ
Error 19 -> SOME ERRORS WERE REPORTED
Error 20 -> NO SERVERS DEFINED
Error 21 -> SERVER END
Error 22 -> SERVER DELETE
Error 23 -> SERVER VALUE
Error 24 -> STAT VALUE
Error 25 -> Gibberish returned!
Error 26 -> SYSTEM ERROR
Error 27 -> COULD NOT OPEN UNIX SOCKET
Error 28 -> ACTION NOT SUPPORTED
Error 29 -> A KEY LENGTH OF ZERO WAS PROVIDED
Error 30 -> FETCH WAS NOT COMPLETED
Error 31 -> A TIMEOUT OCCURRED
Error 32 -> ACTION QUEUED
Error 33 -> A BAD KEY WAS PROVIDED/CHARACTERS OUT OF RANGE
Error 34 -> THE HOST TRANSPORT PROTOCOL DOES NOT MATCH THAT OF THE CLIENT
Error 35 -> SERVER IS MARKED DEAD
Error 36 -> ENCOUNTERED AN UNKNOWN STAT KEY
Error 0 -> SUCCESS
Error 1 -> FAILURE
Error 2 -> HOSTNAME LOOKUP FAILURE
Error 3 -> CONNECTION FAILURE
Error 4 -> CONNECTION BIND FAILURE
Error 5 -> WRITE FAILURE
Error 6 -> READ FAILURE
Error 7 -> UNKNOWN READ FAILURE
Error 8 -> PROTOCOL ERROR
Error 9 -> CLIENT ERROR
Error 10 -> SERVER ERROR
Error 11 -> CONNECTION SOCKET CREATE FAILURE
Error 12 -> CONNECTION DATA EXISTS
Error 13 -> CONNECTION DATA DOES NOT EXIST
Error 14 -> NOT STORED
Error 15 -> STORED
Error 16 -> NOT FOUND
Error 17 -> MEMORY ALLOCATION FAILURE
Error 18 -> PARTIAL READ
Error 19 -> SOME ERRORS WERE REPORTED
Error 20 -> NO SERVERS DEFINED
Error 21 -> SERVER END
Error 22 -> SERVER DELETE
Error 23 -> SERVER VALUE
Error 24 -> STAT VALUE
Error 25 -> Gibberish returned!
Error 26 -> SYSTEM ERROR
Error 27 -> COULD NOT OPEN UNIX SOCKET
Error 28 -> ACTION NOT SUPPORTED
Error 29 -> A KEY LENGTH OF ZERO WAS PROVIDED
Error 30 -> FETCH WAS NOT COMPLETED
Error 31 -> A TIMEOUT OCCURRED
Error 32 -> ACTION QUEUED
Error 33 -> A BAD KEY WAS PROVIDED/CHARACTERS OUT OF RANGE
Error 34 -> THE HOST TRANSPORT PROTOCOL DOES NOT MATCH THAT OF THE CLIENT
Error 35 -> SERVER IS MARKED DEAD
Error 36 -> ENCOUNTERED AN UNKNOWN STAT KEY
Error 0 -> SUCCESS
Error 1 -> FAILURE
Error 2 -> HOSTNAME LOOKUP FAILURE
Error 3 -> CONNECTION FAILURE
Error 4 -> CONNECTION BIND FAILURE
Error 5 -> WRITE FAILURE
Error 6 -> READ FAILURE
Error 7 -> UNKNOWN READ FAILURE
Error 8 -> PROTOCOL ERROR
Error 9 -> CLIENT ERROR
Error 10 -> SERVER ERROR
Error 11 -> CONNECTION SOCKET CREATE FAILURE
Error 12 -> CONNECTION DATA EXISTS
Error 13 -> CONNECTION DATA DOES NOT EXIST
Error 14 -> NOT STORED
Error 15 -> STORED
Error 16 -> NOT FOUND
Error 17 -> MEMORY ALLOCATION FAILURE
Error 18 -> PARTIAL READ
Error 19 -> SOME ERRORS WERE REPORTED
Error 20 -> NO SERVERS DEFINED
Error 21 -> SERVER END
Error 22 -> SERVER DELETE
Error 23 -> SERVER VALUE
Error 24 -> STAT VALUE
Error 25 -> Gibberish returned!
Error 26 -> SYSTEM ERROR
Error 27 -> COULD NOT OPEN UNIX SOCKET
Error 28 -> ACTION NOT SUPPORTED
Error 29 -> A KEY LENGTH OF ZERO WAS PROVIDED
Error 30 -> FETCH WAS NOT COMPLETED
Error 31 -> A TIMEOUT OCCURRED
Error 32 -> ACTION QUEUED
Error 33 -> A BAD KEY WAS PROVIDED/CHARACTERS OUT OF RANGE
Error 34 -> THE HOST TRANSPORT PROTOCOL DOES NOT MATCH THAT OF THE CLIENT
Error 35 -> SERVER IS MARKED DEAD
Error 36 -> ENCOUNTERED AN UNKNOWN STAT KEY
Error 0 -> SUCCESS
Error 1 -> FAILURE
Error 2 -> HOSTNAME LOOKUP FAILURE
Error 3 -> CONNECTION FAILURE
Error 4 -> CONNECTION BIND FAILURE
Error 5 -> WRITE FAILURE
Error 6 -> READ FAILURE
Error 7 -> UNKNOWN READ FAILURE
Error 8 -> PROTOCOL ERROR
Error 9 -> CLIENT ERROR
Error 10 -> SERVER ERROR
Error 11 -> CONNECTION SOCKET CREATE FAILURE
Error 12 -> CONNECTION DATA EXISTS
Error 13 -> CONNECTION DATA DOES NOT EXIST
Error 14 -> NOT STORED
Error 15 -> STORED
Error 16 -> NOT FOUND
Error 17 -> MEMORY ALLOCATION FAILURE
Error 18 -> PARTIAL READ
Error 19 -> SOME ERRORS WERE REPORTED
Error 20 -> NO SERVERS DEFINED
Error 21 -> SERVER END
Error 22 -> SERVER DELETE
Error 23 -> SERVER VALUE
Error 24 -> STAT VALUE
Error 25 -> Gibberish returned!
Error 26 -> SYSTEM ERROR
Error 27 -> COULD NOT OPEN UNIX SOCKET
Error 28 -> ACTION NOT SUPPORTED
Error 29 -> A KEY LENGTH OF ZERO WAS PROVIDED
Error 30 -> FETCH WAS NOT COMPLETED
Error 31 -> A TIMEOUT OCCURRED
Error 32 -> ACTION QUEUED
Error 33 -> A BAD KEY WAS PROVIDED/CHARACTERS OUT OF RANGE
Error 34 -> THE HOST TRANSPORT PROTOCOL DOES NOT MATCH THAT OF THE CLIENT
Error 35 -> SERVER IS MARKED DEAD
Error 36 -> ENCOUNTERED AN UNKNOWN STAT KEY
Error 0 -> SUCCESS
Error 1 -> FAILURE
Error 2 -> HOSTNAME LOOKUP FAILURE
Error 3 -> CONNECTION FAILURE
Error 4 -> CONNECTION BIND FAILURE
Error 5 -> WRITE FAILURE
Error 6 -> READ FAILURE
Error 7 -> UNKNOWN READ FAILURE
Error 8 -> PROTOCOL ERROR
Error 9 -> CLIENT ERROR
Error 10 -> SERVER ERROR
Error 11 -> CONNECTION SOCKET CREATE FAILURE
Error 12 -> CONNECTION DATA EXISTS
Error 13 -> CONNECTION DATA DOES NOT EXIST
Error 14 -> NOT STORED
Error 15 -> STORED
Error 16 -> NOT FOUND
Error 17 -> MEMORY ALLOCATION FAILURE
Error 18 -> PARTIAL READ
Error 19 -> SOME ERRORS WERE REPORTED
Error 20 -> NO SERVERS DEFINED
Error 21 -> SERVER END
Error 22 -> SERVER DELETE
Error 23 -> SERVER VALUE
Error 24 -> STAT VALUE
Error 25 -> Gibberish returned!
Error 26 -> SYSTEM ERROR
Error 27 -> COULD NOT OPEN UNIX SOCKET
Error 28 -> ACTION NOT SUPPORTED
Error 29 -> A KEY LENGTH OF ZERO WAS PROVIDED
Error 30 -> FETCH WAS NOT COMPLETED
Error 31 -> A TIMEOUT OCCURRED
Error 32 -> ACTION QUEUED
Error 33 -> A BAD KEY WAS PROVIDED/CHARACTERS OUT OF RANGE
Error 34 -> THE HOST TRANSPORT PROTOCOL DOES NOT MATCH THAT OF THE CLIENT
Error 35 -> SERVER IS MARKED DEAD
Error 36 -> ENCOUNTERED AN UNKNOWN STAT KEY
Error 0 -> SUCCESS
Error 1 -> FAILURE
Error 2 -> HOSTNAME LOOKUP FAILURE
Error 3 -> CONNECTION FAILURE
Error 4 -> CONNECTION BIND FAILURE
Error 5 -> WRITE FAILURE
Error 6 -> READ FAILURE
Error 7 -> UNKNOWN READ FAILURE
Error 8 -> PROTOCOL ERROR
Error 9 -> CLIENT ERROR
Error 10 -> SERVER ERROR
Error 11 -> CONNECTION SOCKET CREATE FAILURE
Error 12 -> CONNECTION DATA EXISTS
Error 13 -> CONNECTION DATA DOES NOT EXIST
Error 14 -> NOT STORED
Error 15 -> STORED
Error 16 -> NOT FOUND
Error 17 -> MEMORY ALLOCATION FAILURE
Error 18 -> PARTIAL READ
Error 19 -> SOME ERRORS WERE REPORTED
Error 20 -> NO SERVERS DEFINED
Error 21 -> SERVER END
Error 22 -> SERVER DELETE
Error 23 -> SERVER VALUE
Error 24 -> STAT VALUE
Error 25 -> Gibberish returned!
Error 26 -> SYSTEM ERROR
Error 27 -> COULD NOT OPEN UNIX SOCKET
Error 28 -> ACTION NOT SUPPORTED
Error 29 -> A KEY LENGTH OF ZERO WAS PROVIDED
Error 30 -> FETCH WAS NOT COMPLETED
Error 31 -> A TIMEOUT OCCURRED
Error 32 -> ACTION QUEUED
Error 33 -> A BAD KEY WAS PROVIDED/CHARACTERS OUT OF RANGE
Error 34 -> THE HOST TRANSPORT PROTOCOL DOES NOT MATCH THAT OF THE CLIENT
Error 35 -> SERVER IS MARKED DEAD
Error 36 -> ENCOUNTERED AN UNKNOWN STAT KEY
Error 0 -> SUCCESS
Error 1 -> FAILURE
Error 2 -> HOSTNAME LOOKUP FAILURE
Error 3 -> CONNECTION FAILURE
Error 4 -> CONNECTION BIND FAILURE
Error 5 -> WRITE FAILURE
Error 6 -> READ FAILURE
Error 7 -> UNKNOWN READ FAILURE
Error 8 -> PROTOCOL ERROR
Error 9 -> CLIENT ERROR
Error 10 -> SERVER ERROR
Error 11 -> CONNECTION SOCKET CREATE FAILURE
Error 12 -> CONNECTION DATA EXISTS
Error 13 -> CONNECTION DATA DOES NOT EXIST
Error 14 -> NOT STORED
Error 15 -> STORED
Error 16 -> NOT FOUND
Error 17 -> MEMORY ALLOCATION FAILURE
Error 18 -> PARTIAL READ
Error 19 -> SOME ERRORS WERE REPORTED
Error 20 -> NO SERVERS DEFINED
Error 21 -> SERVER END
Error 22 -> SERVER DELETE
Error 23 -> SERVER VALUE
Error 24 -> STAT VALUE
Error 25 -> Gibberish returned!
Error 26 -> SYSTEM ERROR
Error 27 -> COULD NOT OPEN UNIX SOCKET
Error 28 -> ACTION NOT SUPPORTED
Error 29 -> A KEY LENGTH OF ZERO WAS PROVIDED
Error 30 -> FETCH WAS NOT COMPLETED
Error 31 -> A TIMEOUT OCCURRED
Error 32 -> ACTION QUEUED
Error 33 -> A BAD KEY WAS PROVIDED/CHARACTERS OUT OF RANGE
Error 34 -> THE HOST TRANSPORT PROTOCOL DOES NOT MATCH THAT OF THE CLIENT
Error 35 -> SERVER IS MARKED DEAD
Error 36 -> ENCOUNTERED AN UNKNOWN STAT KEY
Error 0 -> SUCCESS
Error 1 -> FAILURE
Error 2 -> HOSTNAME LOOKUP FAILURE
Error 3 -> CONNECTION FAILURE
Error 4 -> CONNECTION BIND FAILURE
Error 5 -> WRITE FAILURE
Error 6 -> READ FAILURE
Error 7 -> UNKNOWN READ FAILURE
Error 8 -> PROTOCOL ERROR
Error 9 -> CLIENT ERROR
Error 10 -> SERVER ERROR
Error 11 -> CONNECTION SOCKET CREATE FAILURE
Error 12 -> CONNECTION DATA EXISTS
Error 13 -> CONNECTION DATA DOES NOT EXIST
Error 14 -> NOT STORED
Error 15 -> STORED
Error 16 -> NOT FOUND
Error 17 -> MEMORY ALLOCATION FAILURE
Error 18 -> PARTIAL READ
Error 19 -> SOME ERRORS WERE REPORTED
Error 20 -> NO SERVERS DEFINED
Error 21 -> SERVER END
Error 22 -> SERVER DELETE
Error 23 -> SERVER VALUE
Error 24 -> STAT VALUE
Error 25 -> Gibberish returned!
Error 26 -> SYSTEM ERROR
Error 27 -> COULD NOT OPEN UNIX SOCKET
Error 28 -> ACTION NOT SUPPORTED
Error 29 -> A KEY LENGTH OF ZERO WAS PROVIDED
Error 30 -> FETCH WAS NOT COMPLETED
Error 31 -> A TIMEOUT OCCURRED
Error 32 -> ACTION QUEUED
Error 33 -> A BAD KEY WAS PROVIDED/CHARACTERS OUT OF RANGE
Error 34 -> THE HOST TRANSPORT PROTOCOL DOES NOT MATCH THAT OF THE CLIENT
Error 35 -> SERVER IS MARKED DEAD
Error 36 -> ENCOUNTERED AN UNKNOWN STAT KEY
Error 0 -> SUCCESS
Error 1 -> FAILURE
Error 2 -> HOSTNAME LOOKUP FAILURE
Error 3 -> CONNECTION FAILURE
Error 4 -> CONNECTION BIND FAILURE
Error 5 -> WRITE FAILURE
Error 6 -> READ FAILURE
Error 7 -> UNKNOWN READ FAILURE
Error 8 -> PROTOCOL ERROR
Error 9 -> CLIENT ERROR
Error 10 -> SERVER ERROR
Error 11 -> CONNECTION SOCKET CREATE FAILURE
Error 12 -> CONNECTION DATA EXISTS
Error 13 -> CONNECTION DATA DOES NOT EXIST
Error 14 -> NOT STORED
Error 15 -> STORED
Error 16 -> NOT FOUND
Error 17 -> MEMORY ALLOCATION FAILURE
Error 18 -> PARTIAL READ
Error 19 -> SOME ERRORS WERE REPORTED
Error 20 -> NO SERVERS DEFINED
Error 21 -> SERVER END
Error 22 -> SERVER DELETE
Error 23 -> SERVER VALUE
Error 24 -> STAT VALUE
Error 25 -> Gibberish returned!
Error 26 -> SYSTEM ERROR
Error 27 -> COULD NOT OPEN UNIX SOCKET
Error 28 -> ACTION NOT SUPPORTED
Error 29 -> A KEY LENGTH OF ZERO WAS PROVIDED
Error 30 -> FETCH WAS NOT COMPLETED
Error 31 -> A TIMEOUT OCCURRED
Error 32 -> ACTION QUEUED
Error 33 -> A BAD KEY WAS PROVIDED/CHARACTERS OUT OF RANGE
Error 34 -> THE HOST TRANSPORT PROTOCOL DOES NOT MATCH THAT OF THE CLIENT
Error 35 -> SERVER IS MARKED DEAD
Error 36 -> ENCOUNTERED AN UNKNOWN STAT KEY
Error 0 -> SUCCESS
Error 1 -> FAILURE
Error 2 -> HOSTNAME LOOKUP FAILURE
Error 3 -> CONNECTION FAILURE
Error 4 -> CONNECTION BIND FAILURE
Error 5 -> WRITE FAILURE
Error 6 -> READ FAILURE
Error 7 -> UNKNOWN READ FAILURE
Error 8 -> PROTOCOL ERROR
Error 9 -> CLIENT ERROR
Error 10 -> SERVER ERROR
Error 11 -> CONNECTION SOCKET CREATE FAILURE
Error 12 -> CONNECTION DATA EXISTS
Error 13 -> CONNECTION DATA DOES NOT EXIST
Error 14 -> NOT STORED
Error 15 -> STORED
Error 16 -> NOT FOUND
Error 17 -> MEMORY ALLOCATION FAILURE
Error 18 -> PARTIAL READ
Error 19 -> SOME ERRORS WERE REPORTED
Error 20 -> NO SERVERS DEFINED
Error 21 -> SERVER END
Error 22 -> SERVER DELETE
Error 23 -> SERVER VALUE
Error 24 -> STAT VALUE
Error 25 -> Gibberish returned!
Error 26 -> SYSTEM ERROR
Error 27 -> COULD NOT OPEN UNIX SOCKET
Error 28 -> ACTION NOT SUPPORTED
Error 29 -> A KEY LENGTH OF ZERO WAS PROVIDED
Error 30 -> FETCH WAS NOT COMPLETED
Error 31 -> A TIMEOUT OCCURRED
Error 32 -> ACTION QUEUED
Error 33 -> A BAD KEY WAS PROVIDED/CHARACTERS OUT OF RANGE
Error 34 -> THE HOST TRANSPORT PROTOCOL DOES NOT MATCH THAT OF THE CLIENT
Error 35 -> SERVER IS MARKED DEAD
Error 36 -> ENCOUNTERED AN UNKNOWN STAT KEY
Error 0 -> SUCCESS
Error 1 -> FAILURE
Error 2 -> HOSTNAME LOOKUP FAILURE
Error 3 -> CONNECTION FAILURE
Error 4 -> CONNECTION BIND FAILURE
Error 5 -> WRITE FAILURE
Error 6 -> READ FAILURE
Error 7 -> UNKNOWN READ FAILURE
Error 8 -> PROTOCOL ERROR
Error 9 -> CLIENT ERROR
Error 10 -> SERVER ERROR
Error 11 -> CONNECTION SOCKET CREATE FAILURE
Error 12 -> CONNECTION DATA EXISTS
Error 13 -> CONNECTION DATA DOES NOT EXIST
Error 14 -> NOT STORED
Error 15 -> STORED
Error 16 -> NOT FOUND
Error 17 -> MEMORY ALLOCATION FAILURE
Error 18 -> PARTIAL READ
Error 19 -> SOME ERRORS WERE REPORTED
Error 20 -> NO SERVERS DEFINED
Error 21 -> SERVER END
Error 22 -> SERVER DELETE
Error 23 -> SERVER VALUE
Error 24 -> STAT VALUE
Error 25 -> Gibberish returned!
Error 26 -> SYSTEM ERROR
Error 27 -> COULD NOT OPEN UNIX SOCKET
Error 28 -> ACTION NOT SUPPORTED
Error 29 -> A KEY LENGTH OF ZERO WAS PROVIDED
Error 30 -> FETCH WAS NOT COMPLETED
Error 31 -> A TIMEOUT OCCURRED
Error 32 -> ACTION QUEUED
Error 33 -> A BAD KEY WAS PROVIDED/CHARACTERS OUT OF RANGE
Error 34 -> THE HOST TRANSPORT PROTOCOL DOES NOT MATCH THAT OF THE CLIENT
Error 35 -> SERVER IS MARKED DEAD
Error 36 -> ENCOUNTERED AN UNKNOWN STAT KEY
